Adds support for idempotent producers
spirit-labs/tektite pull request #217
Opened 2024-08-16 06:22 UTC by jlerche

2024-08-16 06:50 UTC, purplefox commented on kafkaserver/handler.go
> +			producerID := int(binary.BigEndian.Uint64(producedRecords[43:51]))
I think we should move this chunk of code to KafkaInOperator.HandleStreamBatch - this is called on the eventloop with the batch. Then you can extract the producer id and sequence there and lookup from the map stored there

2024-08-16 06:51 UTC, purplefox commented on kafkaserver/handler.go
> +					partitionResponses[j].ErrorCode = protocol.ErrorCodeDuplicateSequenceNumber
And will need to return the other error code if there are gaps in the sequence (see KIP)

2024-08-31 18:31 UTC, purplefox commented
Hi @jlerche - just wondering how this is going? Do you need any help? :)

2024-09-04 05:02 UTC, jlerche commented
> Hi @jlerche - just wondering how this is going? Do you need any help? :)

Should be ready to go! @purplefox

2024-09-04 10:11 UTC, purplefox requested changes
Looking good, just a couple of comments.

I think we also need a test which tests it works with an actual client. Perhaps take a look at integration/producer_endpoint_test.go or integration/kafka_api_test.go

2024-09-04 10:11 UTC, purplefox commented on opers/kafka_in.go
> +			panic("unexpected processor ID")
best to return error not panic

2024-09-04 10:11 UTC, purplefox commented on opers/kafka_in.go
> +		if k.partitionProducerMapping[processorID][partitionID] == nil {
If you store this in a local variable you can avoid the double lookup multiple times

2024-09-04 18:58 UTC, jlerche commented
> Looking good, just a couple of comments.
> 
> I think we also need a test which tests it works with an actual client. Perhaps take a look at integration/producer_endpoint_test.go or integration/kafka_api_test.go

I enabled idempotence in the go client part of `producer_endpoint_test.go`. I could add it to the java one too and then have them both run their test with and without idempotency, what do you think?

2024-09-05 20:50 UTC, purplefox commented
OK thank you!
Perhaps you could. do a quick manual test and stick a breakpoint in your IDE where the dedup code occurs and make sure it is called when running the producer endpoint test?

2024-09-05 20:50 UTC, merged

2024-09-05 21:53 UTC, jlerche commented
Sure, here's a screenshot when running the test

![image](https://github.com/user-attachments/assets/edd7b77e-fed1-4def-bf09-4b0ff70af946)